Front end
idrismahamdi/AC41004---Industrial-Team-Project pull request #58
Opened 2022-10-04 16:19 UTC by jweir211

for the page template

2022-10-05 08:27 UTC, Arcfej requested changes
I reviewed only the index.html and master.css, as that's what I think you intended as a template. I added a requested change and some suggestions. Due to the short amount of time, you may ignore the suggestions, but I think they would improve teamwork. I'd also like to ask, and Idris also mentioned this on Teams, to convert the html files to php, so that we can easily use them on the backend.

2022-10-05 14:48 UTC, jweir211 commented on Pages/styling/master.css
> +}
this is not for a colour? It is to stop tghe list of rules running down off the page and allow for the scroller

2022-10-05 15:23 UTC, jweir211 commented on Pages/index.html
> +    <nav class="navbar navbar-expand-lg fixed-top navbar-dark navbar-expand border" style="background-color: #115E67;">
Must leave as is. bootstrap css overwrites my css for bg-primary

2022-10-09 10:53 UTC, Arcfej commented
Changes have been merged by another PR

2022-10-09 10:53 UTC, closed without merging